# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-ubuntu:3.14"
  amd64: "ghcr.io/home-assistant/amd64-base-ubuntu:3.14"
  armhf: "ghcr.io/home-assistant/armhf-base-ubuntu:3.14"
  armv7: "ghcr.io/home-assistant/armv7-base-ubuntu:3.14"
  i386: "ghcr.io/home-assistant/i386-base-ubuntu:3.14"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Metabase"
  org.opencontainers.image.description: "Home Assistant Add-on: Metabase"
  org.opencontainers.image.source: "https://github.com/sanderdw/hassio-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "0.4.0"