# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Metabase
version: "develop"
slug: metabase
description: Meet the easy, open source way for everyone to ask questions and learn from data.
url: "https://github.com/sanderdw/hassio-addons/blob/master/metabase/README.md"
startup: application
ports:
  3000/tcp: 7778
network:
  3000/tcp: Web interface (Ingress not working yet)
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
init: false
options:
  MB_DB_DBNAME: "metabase"
  MB_DB_USER: "postgres"
  MB_DB_PASS: "homeassistant"
  MB_DB_HOST: "77b2833f-timescaledb"
  MB_DB_PORT: "5432"
schema:
  MB_DB_DBNAME: "str"
  MB_DB_USER: "str"
  MB_DB_PASS: "password"
  MB_DB_HOST: "str"
  MB_DB_PORT: "str"
image: sanderdw/ha-metabase