name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_TARGET_REPO: sanderdw/hassio-addons
  DOCKERFILE: metabase/Dockerfile
  DOCKER_TARGET_RELEASE: 2022.04.11

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # AMD64
          - BUILD_FROM: amd64-base-ubuntu
            QEMU_ARCH: x86_64
            S6_ARCH: amd64
            DOCKER_TAG_SUFFIX: amd64

          # ARM32V7
          - BUILD_FROM: armv7-base-ubuntu
            QEMU_ARCH: arm
            S6_ARCH: armhf
            DOCKER_TAG_SUFFIX: arm32v7

          # ARM64V8
          - BUILD_FROM: aarch64-base-ubuntu
            QEMU_ARCH: aarch64
            S6_ARCH: aarch64
            DOCKER_TAG_SUFFIX: arm64v8

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          echo "DOCKER BUILD: BUILD_FROM - ${{matrix.BUILD_FROM}}."
          docker build -f ${DOCKERFILE} \
            --build-arg BUILD_FROM=${{ matrix.BUILD_FROM }} \
            --build-arg QEMU_ARCH=${{ matrix.QEMU_ARCH }} \
            --build-arg S6_ARCH=${{ matrix.S6_ARCH }} \
            --build-arg DSMR_VERSION=${{ steps.dsmr_version.outputs.version }} \
            --build-arg DOCKER_TARGET_RELEASE=${DOCKER_TARGET_RELEASE} \
            -t ${DOCKER_TARGET_REPO}:latest \
            .
