name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # AMD64
          - BASE_IMAGE: amd64-base-ubuntu
            QEMU_ARCH: x86_64
            S6_ARCH: amd64
            DOCKER_TAG_SUFFIX: amd64

          # ARM32V7
          - BASE_IMAGE: armv7-base-ubuntu
            QEMU_ARCH: arm
            S6_ARCH: armhf
            DOCKER_TAG_SUFFIX: arm32v7

          # ARM64V8
          - BASE_IMAGE: aarch64-base-ubuntu
            QEMU_ARCH: aarch64
            S6_ARCH: aarch64
            DOCKER_TAG_SUFFIX: arm64v8

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file metabase/Dockerfile --tag my-metabase:$(date +%s)
