name: DSMR Datalogger

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'datalogger'
    tags:
      - 'v*.*.*'
    paths:
      - 'dsmr_datalogger/Dockerfile'
      - 'dsmr_datalogger/dsmr_datalogger_api_client.py'
      - '.github/workflows/dsmr-datalogger.yml'
      - 'dsmr_datalogger/run.sh'
      - 'dsmr_datalogger/config.json'

jobs:
  dsmr-datalogger:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # AMD64
          - DOCKER_TAG_SUFFIX: amd64
            S6_ARCH: amd64
            BASE_IMAGE: homeassistant/amd64-base-python:3.9
            PLATFORMS: linux/amd64
            QEMU_ARCH: x86_64

          # ARM32V6
          - DOCKER_TAG_SUFFIX: armhf
            S6_ARCH: armhf
            BASE_IMAGE: homeassistant/armhf-base-python:3.9
            PLATFORMS: linux/arm/v6
            QEMU_ARCH: arm

          # ARM32V7
          - DOCKER_TAG_SUFFIX: armv7
            S6_ARCH: armv7
            BASE_IMAGE: homeassistant/armv7-base-python:3.9
            PLATFORMS: linux/arm/v7
            QEMU_ARCH: arm

          # ARM64V8
          - DOCKER_TAG_SUFFIX: aarch64
            S6_ARCH: aarch64
            BASE_IMAGE: homeassistant/aarch64-base-python:3.9
            PLATFORMS: linux/arm64
            QEMU_ARCH: aarch64

          # i386
          - DOCKER_TAG_SUFFIX: i386
            S6_ARCH: i386
            BASE_IMAGE: homeassistant/i386-base-python:3.9
            PLATFORMS: linux/i386
            QEMU_ARCH: i386

    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Get the version from config.json
        id: data
        run: |
          version=$(jq --raw-output '.version' ./dsmr_datalogger/config.json)
          echo "::set-output name=HA_RELEASE::$version"
      - name: DSMR addon release
        run: echo ${{ steps.data.outputs.HA_RELEASE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta # you'll use this in the next step
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            sanderdw/ha-dsmr-datalogger-${{ matrix.DOCKER_TAG_SUFFIX }}
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=${{ steps.data.outputs.HA_RELEASE }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./dsmr_datalogger
          platforms: ${{ steps.data.outputs.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_FROM=${{matrix.BASE_IMAGE}}
            HA_RELEASE=${{ steps.data.outputs.HA_RELEASE }}
            BUILD_ARCH=${{matrix.S6_ARCH}}